_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 75
                - 95
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
                - 75
                - 95
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.0
            "6": 4.30.2
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
K:
    value: 3
goal:
    value: Here are some forecasters' reationales for their predictions. I want to understand what features are important for accurate forecasts.
labels_length:
    value: 50
texts_length:
    value: 50
